config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :collisions
  resources :data
  resources :weathers
  resources :reports
  resources :flights
  resources :aircrafts
  resources :pilots
  resources :birds
  resources :airports
  resources :cities
  resources :states
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  root to: "airports#index"
end

app/models/ability.rb
# frozen_string_literal: true

class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
       user ||= User.new # guest user (not logged in)
       if user.id == 1
        can :manage, :all
       elsif user.id != nil
        can :read, :all
        cannot :read, User
        cannot :show, :all
        can :read, User, :id => user.id
        can :update, User, :id => user.id
       else
        can :read, [Airport,Bird]
        cannot :show, [Airport,Bird]
        can :create, User
       end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/aircraft.rb
class Aircraft < ApplicationRecord
    has_many :flights

    validates :category, :certification, :model, presence: true

    paginates_per 8

    def model_certification
        model + " (" + certification + ")"
    end
end

app/models/airport.rb
class Airport < ApplicationRecord
  belongs_to :city
  has_many :data
  has_many :collisions, through: :data

  validates :name, presence: true, uniqueness: true
  validates :category, presence: true

  paginates_per 8
end

app/models/bird.rb
class Bird < ApplicationRecord
    has_many :collisions

    validates :common_name, :scientific_name, presence: true, uniqueness: true

    paginates_per 8
end

app/models/city.rb
class City < ApplicationRecord
  belongs_to :state
  has_many :airports

  validates :name, presence: true

  paginates_per 8
end

app/models/collision.rb
class Collision < ApplicationRecord
  belongs_to :bird
  belongs_to :datum

  paginates_per 8
end

app/models/datum.rb
class Datum < ApplicationRecord
  belongs_to :airport
  belongs_to :flight
  belongs_to :weather
  belongs_to :report
  has_many :collisions

  validates :date, :flight_phase, presence: true

  paginates_per 8
end

app/models/flight.rb
class Flight < ApplicationRecord
  belongs_to :aircraft
  belongs_to :pilot
  has_many :data

  paginates_per 8
end

app/models/pilot.rb
class Pilot < ApplicationRecord
    has_many :flights

    validates :first_name, :last_name, :privilege_level, :document, :birth_date, presence: true
    validates :document, uniqueness: true

    paginates_per 8

    def full_name
        last_name + ", " + first_name
    end
end

app/models/report.rb
class Report < ApplicationRecord
    has_many :data

    validates :airline_expense, :airport_expense, :insurance_expense, :public_expense, :delayed_flights, :fatal_victims, presence: true

    paginates_per 8
end

app/models/state.rb
class State < ApplicationRecord
    has_many :cities
    
    validates :name, presence: true, uniqueness: true
    
    paginates_per 8
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/weather.rb
class Weather < ApplicationRecord
    has_many :data

    validates :celsius_temperature, :humidity, :wind_speed, :average_rainfall, :insolation, presence: true

    paginates_per 8
end

app/helpers/birds_helper.rb
module BirdsHelper
end

app/helpers/cities_helper.rb
module CitiesHelper
end

app/helpers/data_helper.rb
module DataHelper
end

app/helpers/flights_helper.rb
module FlightsHelper
end

app/helpers/pilots_helper.rb
module PilotsHelper
end

app/helpers/reports_helper.rb
module ReportsHelper
end

app/helpers/states_helper.rb
module StatesHelper
end

app/views/shared/_footer.html.erb
<div class="container" style="margin-top: 30px">
    <nav class="navbar navbar-expand-xl navbar-light fixed-bottom" style="background-color: #937206;">
        <%= render "shared/user_menu" %>
    </nav>
</div>

app/views/shared/_menu.html.erb
<ul class="navbar-nav me-auto mb-2 mb-xl-0">
  <li class="nav-item">
    <% if can? :read, State %><%= link_to "States", states_url, class: "nav-link active" %><% end %>
  </li>
  <li class="nav-item">
    <% if can? :read, City %><%= link_to "Cities", cities_url, class: "nav-link active" %><% end %>
  </li>
  <li class="nav-item">
    <% if can? :read, Airport %><%= link_to "Airports", airports_url, class: "nav-link active" %><% end %>
  </li>
  <li class="nav-item">
    <% if can? :read, Bird %><%= link_to "Birds", birds_url, class: "nav-link active" %><% end %>
  </li>
  <li class="nav-item">
    <% if can? :read, Pilot %><%= link_to "Pilots", pilots_url, class: "nav-link active" %><% end %>
  </li>
  <li class="nav-item">
    <% if can? :read, Aircraft %><%= link_to "Aircrafts", aircrafts_url, class: "nav-link active" %><% end %>
  </li>
  <li class="nav-item">
    <% if can? :read, Flight %>
      <% if current_user.id == 1 %>
        <%= link_to "Flights", flights_url, class: "nav-link active" %>
      <% end %>
    <% end %>
  </li>
  <li class="nav-item">
    <% if can? :read, Report %>
      <% if current_user.id == 1 %>
        <%= link_to "Reports", reports_url, class: "nav-link active" %>
      <% end %>
    <% end %>
  </li>
  <li class="nav-item">
    <% if can? :read, Weather %>
      <% if current_user.id == 1 %>
        <%= link_to "Weathers", weathers_url, class: "nav-link active" %>
      <% end %>
    <% end %>
  </li>
  <li class="nav-item">
    <% if can? :read, Datum %>
      <% if current_user.id == 1 %>
        <%= link_to "Data", data_url, class: "nav-link active" %>
      <% end %>
    <% end %>
  </li>
  <li class="nav-item">
    <% if can? :read, Collision %>
      <% if current_user.id == 1 %>
        <%= link_to "Collisions", collisions_url, class: "nav-link active" %>
      <% end %>
    <% end %>
  </li>
</ul>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-xl navbar-dark" style="background-color: #003e7e;">
  <div class="container-fluid">
    <a class="navbar-brand" href="<%= root_url %>"><img src="https://upload.wikimedia.org/wikipedia/commons/thumb/c/c8/Seal_of_the_United_States_Federal_Aviation_Administration.svg/1200px-Seal_of_the_United_States_Federal_Aviation_Administration.svg.png" alt="FAA" width="40" height="40"></a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarDark"
      aria-controls="navbarDark" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse show" id="navbarDark">
      
      <%= render "shared/menu" %>

    </div>
  </div>
</nav>

app/views/shared/_user_menu.html.erb
<div class="btn-group dropup">
  <% if user_signed_in? %>
    <button type="button" class="btn dropdown-toggle ms-3" style="background-color: #efefef;" data-bs-toggle="dropdown" aria-expanded="false">
      <span style="color:black"><%= current_user.email %></span>
    </button>
    <ul class="dropdown-menu ms-3">
      <li><%= link_to "Settings", edit_user_registration_path, class: "dropdown-item" %></li>
      <li><%= link_to "Log out", destroy_user_session_path, class: "dropdown-item",  method: :delete  %></li>
    </ul>
    <% else %>
      <%= link_to "Log in", new_user_session_url, class: 'btn btn-secondary ms-3' %>
    <% end %>
</div>