config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :collisions
  resources :data
  resources :weathers
  resources :reports
  resources :flights
  resources :aircrafts
  resources :pilots
  resources :birds
  resources :airports
  resources :cities
  resources :states
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  root to: "airports#index"
end

app/models/ability.rb
# frozen_string_literal: true

class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
       user ||= User.new # guest user (not logged in)
       if user.id == 1
        can :manage, :all
       elsif user.id != nil
        can :read, :all
        cannot :read, User
        cannot :show, :all
        can :read, User, :id => user.id
        can :update, User, :id => user.id
       else
        can :read, [Airport,Bird]
        cannot :show, [Airport,Bird]
        can :create, User
       end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/aircraft.rb
class Aircraft < ApplicationRecord
    has_many :flights

    validates :category, :certification, :model, presence: true

    paginates_per 8

    def model_certification
        model + " (" + certification + ")"
    end
end

app/models/airport.rb
class Airport < ApplicationRecord
  belongs_to :city
  has_many :data
  has_many :collisions, through: :data

  validates :name, presence: true, uniqueness: true
  validates :category, presence: true

  paginates_per 8
end

app/models/bird.rb
class Bird < ApplicationRecord
    has_many :collisions

    validates :common_name, :scientific_name, presence: true, uniqueness: true

    paginates_per 8
end

app/models/city.rb
class City < ApplicationRecord
  belongs_to :state
  has_many :airports

  validates :name, presence: true

  paginates_per 8
end

app/models/collision.rb
class Collision < ApplicationRecord
  belongs_to :bird
  belongs_to :datum

  paginates_per 8
end

app/models/datum.rb
class Datum < ApplicationRecord
  belongs_to :airport
  belongs_to :flight
  belongs_to :weather
  belongs_to :report
  has_many :collisions

  validates :date, :flight_phase, presence: true

  paginates_per 8
end

app/models/flight.rb
class Flight < ApplicationRecord
  belongs_to :aircraft
  belongs_to :pilot
  has_many :data

  paginates_per 8
end

app/models/pilot.rb
class Pilot < ApplicationRecord
    has_many :flights

    validates :first_name, :last_name, :privilege_level, :document, :birth_date, presence: true
    validates :document, uniqueness: true

    paginates_per 8

    def full_name
        last_name + ", " + first_name
    end
end

app/models/report.rb
class Report < ApplicationRecord
    has_many :data

    validates :airline_expense, :airport_expense, :insurance_expense, :public_expense, :delayed_flights, :fatal_victims, presence: true

    paginates_per 8
end

app/models/state.rb
class State < ApplicationRecord
    has_many :cities
    
    validates :name, presence: true, uniqueness: true
    
    paginates_per 8
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/weather.rb
class Weather < ApplicationRecord
    has_many :data

    validates :celsius_temperature, :humidity, :wind_speed, :average_rainfall, :insolation, presence: true

    paginates_per 8
end

app/controllers/pilots_controller.rb
class PilotsController < ApplicationController
  before_action :set_pilot, only: %i[ show edit update destroy ]
  load_and_authorize_resource

  # GET /pilots or /pilots.json
  def index
    @pilots = Pilot.all
    @pilots = @pilots.where("first_name LIKE :filter OR last_name LIKE :filter", filter: "%" + params[:filter] + "%") unless params[:filter].blank?
    @pilots = @pilots.where("document LIKE :document", document: "%" + params[:document] + "%") unless params[:document].blank?
    @pilots = @pilots.order(params[:by] + " " + params[:order]) if params[:sort] == "true"
    @pilots = @pilots.page(params[:page] || 1)
  end

  # GET /pilots/1 or /pilots/1.json
  def show
  end

  # GET /pilots/new
  def new
    @pilot = Pilot.new
  end

  # GET /pilots/1/edit
  def edit
  end

  # POST /pilots or /pilots.json
  def create
    @pilot = Pilot.new(pilot_params)

    respond_to do |format|
      if @pilot.save
        format.html { redirect_to @pilot, notice: "Pilot was successfully created." }
        format.json { render :show, status: :created, location: @pilot }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @pilot.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pilots/1 or /pilots/1.json
  def update
    respond_to do |format|
      if @pilot.update(pilot_params)
        format.html { redirect_to @pilot, notice: "Pilot was successfully updated." }
        format.json { render :show, status: :ok, location: @pilot }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @pilot.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pilots/1 or /pilots/1.json
  def destroy
    @pilot.destroy
    respond_to do |format|
      format.html { redirect_to pilots_url, notice: "Pilot was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pilot
      @pilot = Pilot.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def pilot_params
      params.require(:pilot).permit(:first_name, :last_name, :privilege_level, :document, :birth_date)
    end
end

app/helpers/airports_helper.rb
module AirportsHelper
end

app/helpers/birds_helper.rb
module BirdsHelper
end

app/helpers/cities_helper.rb
module CitiesHelper
end

app/helpers/data_helper.rb
module DataHelper
end

app/helpers/flights_helper.rb
module FlightsHelper
end

app/helpers/pilots_helper.rb
module PilotsHelper
end

app/helpers/reports_helper.rb
module ReportsHelper
end

app/helpers/states_helper.rb
module StatesHelper
end

app/helpers/weathers_helper.rb
module WeathersHelper
end

app/views/pilots/_form.html.erb
<%= form_with(model: pilot) do |form| %>
  <% if pilot.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(pilot.errors.count, "error") %> prohibited this pilot from being saved:</h2>

      <ul>
        <% pilot.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :first_name %>
    <%= form.text_field :first_name %>
  </div>

  <div class="field">
    <%= form.label :last_name %>
    <%= form.text_field :last_name %>
  </div>

  <div class="field">
    <%= form.label :privilege_level %>
    <select name="pilot[privilege_level]">
      <option value="Student pilot">Student pilot</option>
      <option value="Sport pilot">Sport pilot</option>
      <option value="Recreational pilot">Recreational pilot</option>
      <option value="Private pilot">Private pilot</option>
      <option value="Commercial pilot">Commercial pilot</option>
      <option value="Airline transport pilot">Airline transport pilot</option>
      <option value="Remote pilot">Remote pilot</option>
    </select>
  </div>

  <div class="field">
    <%= form.label :document %>
    <%= form.number_field :document %>
  </div>

  <div class="field">
    <%= form.label :birth_date %>
    <%= form.date_select :birth_date, start_year: 1914, end_year: (Date.current.year - 18), use_two_digit_numbers: true, order: [:day,:month,:year] %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/pilots/edit.html.erb
<h1>Editing Pilot</h1>

<%= render 'form', pilot: @pilot %>

<%= link_to 'Show', @pilot %> |
<%= link_to 'Back', pilots_path %>

app/views/pilots/index.html.erb
<p id="notice"><%= notice %></p>

<div class="d-flex justify-content-between">
  <div><h1>Pilots</h1></div>
  <div class="ms-5"><%= paginate @pilots, window: 3, outer_window: 3 %></div>
</div>
  <form method="GET" action="/pilots">
    Name: <input type="text" name="filter" placeholder="pilot name" /><br>
    Document: <input type="text" name="document" placeholder="document number" />
    <input type="submit" value="Search"/>
  </form><br>

<table class="table table-striped table-hover">
  <thead class="table-dark">
    <tr>
      <th><%= link_to "First name", pilots_url(sort: true, by: "first_name", order: (params[:order] == "asc" ? "desc" : "asc")), class: 'text-decoration-none text-light' %></th>
      <th><%= link_to "Last name", pilots_url(sort: true, by: "last_name", order: (params[:order] == "asc" ? "desc" : "asc")), class: 'text-decoration-none text-light' %></th>
      <th>Privilege level</th>
      <th>Document</th>
      <th>Birth date</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @pilots.each do |pilot| %>
      <tr>
        <td><%= pilot.first_name %></td>
        <td><%= pilot.last_name %></td>
        <td><%= pilot.privilege_level %></td>
        <td><%= link_to pilot.document, flights_url(pilot_id: pilot.id), class: 'text-decoration-none' %></td>
        <td><%= pilot.birth_date.to_formatted_s(:long_ordinal) %></td>
        <td><% if can? :show, Pilot %><%= link_to 'Show', pilot, class: 'btn btn-sm btn-primary' %><% end %></td>
        <td><% if can? :update, Pilot %><%= link_to 'Edit', edit_pilot_path(pilot), class: 'btn btn-sm btn-secondary' %><% end %></td>
        <td><% if can? :destroy, Pilot %><%= link_to 'Destroy', pilot, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-sm btn-danger' %><% end %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<% if can? :create, Pilot %><%= link_to 'New Pilot', new_pilot_path, class: 'btn btn-sm btn-success' %><% end %>

app/views/pilots/new.html.erb
<h1>New Pilot</h1>

<%= render 'form', pilot: @pilot %>

<%= link_to 'Back', pilots_path %>

app/views/pilots/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>First name:</strong>
  <%= @pilot.first_name %>
</p>

<p>
  <strong>Last name:</strong>
  <%= @pilot.last_name %>
</p>

<p>
  <strong>Privilege level:</strong>
  <%= @pilot.privilege_level %>
</p>

<p>
  <strong>Document:</strong>
  <%= @pilot.document %>
</p>

<p>
  <strong>Birth date:</strong>
  <%= @pilot.birth_date.to_formatted_s(:long_ordinal) %>
</p>

<%= link_to 'Edit', edit_pilot_path(@pilot) %> |
<%= link_to 'Back', pilots_path %>