config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :collisions
  resources :data
  resources :weathers
  resources :reports
  resources :flights
  resources :aircrafts
  resources :pilots
  resources :birds
  resources :airports
  resources :cities
  resources :states
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  root to: "airports#index"
end

app/models/ability.rb
# frozen_string_literal: true

class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
       user ||= User.new # guest user (not logged in)
       if user.id == 1
        can :manage, :all
       elsif user.id != nil
        can :read, :all
        cannot :read, User
        cannot :show, :all
        can :read, User, :id => user.id
        can :update, User, :id => user.id
       else
        can :read, [Airport,Bird]
        cannot :show, [Airport,Bird]
        can :create, User
       end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/aircraft.rb
class Aircraft < ApplicationRecord
    has_many :flights

    validates :category, :certification, :model, presence: true

    paginates_per 8

    def model_certification
        model + " (" + certification + ")"
    end
end

app/models/airport.rb
class Airport < ApplicationRecord
  belongs_to :city
  has_many :data
  has_many :collisions, through: :data

  validates :name, presence: true, uniqueness: true
  validates :category, presence: true

  paginates_per 8
end

app/models/bird.rb
class Bird < ApplicationRecord
    has_many :collisions

    validates :common_name, :scientific_name, presence: true, uniqueness: true

    paginates_per 8
end

app/models/city.rb
class City < ApplicationRecord
  belongs_to :state
  has_many :airports

  validates :name, presence: true

  paginates_per 8
end

app/models/collision.rb
class Collision < ApplicationRecord
  belongs_to :bird
  belongs_to :datum

  paginates_per 8
end

app/models/datum.rb
class Datum < ApplicationRecord
  belongs_to :airport
  belongs_to :flight
  belongs_to :weather
  belongs_to :report
  has_many :collisions

  validates :date, :flight_phase, presence: true

  paginates_per 8
end

app/models/flight.rb
class Flight < ApplicationRecord
  belongs_to :aircraft
  belongs_to :pilot
  has_many :data

  paginates_per 8
end

app/models/pilot.rb
class Pilot < ApplicationRecord
    has_many :flights

    validates :first_name, :last_name, :privilege_level, :document, :birth_date, presence: true
    validates :document, uniqueness: true

    paginates_per 8

    def full_name
        last_name + ", " + first_name
    end
end

app/models/report.rb
class Report < ApplicationRecord
    has_many :data

    validates :airline_expense, :airport_expense, :insurance_expense, :public_expense, :delayed_flights, :fatal_victims, presence: true

    paginates_per 8
end

app/models/state.rb
class State < ApplicationRecord
    has_many :cities
    
    validates :name, presence: true, uniqueness: true
    
    paginates_per 8
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/weather.rb
class Weather < ApplicationRecord
    has_many :data

    validates :celsius_temperature, :humidity, :wind_speed, :average_rainfall, :insolation, presence: true

    paginates_per 8
end

app/controllers/collisions_controller.rb
class CollisionsController < ApplicationController
  before_action :set_collision, only: %i[ show edit update destroy ]
  load_and_authorize_resource

  # GET /collisions or /collisions.json
  def index
    @collisions = Collision.all
    @collisions = @collisions.where(bird_id: params[:bird_id]) unless params[:bird_id].blank?
    @collisions = @collisions.page(params[:page] || 1)
  end

  # GET /collisions/1 or /collisions/1.json
  def show
  end

  # GET /collisions/new
  def new
    @collision = Collision.new
  end

  # GET /collisions/1/edit
  def edit
  end

  # POST /collisions or /collisions.json
  def create
    @collision = Collision.new(collision_params)

    respond_to do |format|
      if @collision.save
        format.html { redirect_to @collision, notice: "Collision was successfully created." }
        format.json { render :show, status: :created, location: @collision }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @collision.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /collisions/1 or /collisions/1.json
  def update
    respond_to do |format|
      if @collision.update(collision_params)
        format.html { redirect_to @collision, notice: "Collision was successfully updated." }
        format.json { render :show, status: :ok, location: @collision }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @collision.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /collisions/1 or /collisions/1.json
  def destroy
    @collision.destroy
    respond_to do |format|
      format.html { redirect_to collisions_url, notice: "Collision was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_collision
      @collision = Collision.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def collision_params
      params.require(:collision).permit(:bird_id, :datum_id)
    end
end

app/helpers/airports_helper.rb
module AirportsHelper
end

app/helpers/birds_helper.rb
module BirdsHelper
end

app/helpers/cities_helper.rb
module CitiesHelper
end

app/helpers/collisions_helper.rb
module CollisionsHelper
end

app/helpers/data_helper.rb
module DataHelper
end

app/helpers/flights_helper.rb
module FlightsHelper
end

app/helpers/pilots_helper.rb
module PilotsHelper
end

app/helpers/reports_helper.rb
module ReportsHelper
end

app/helpers/states_helper.rb
module StatesHelper
end

app/views/collisions/_form.html.erb
<%= form_with(model: collision) do |form| %>
  <% if collision.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(collision.errors.count, "error") %> prohibited this collision from being saved:</h2>

      <ul>
        <% collision.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :bird_id %>
    <%= form.collection_select(:bird_id, Bird.all, :id, :common_name) %>
  </div>

  <div class="field">
    <%= form.label :datum_id %>
    <input type="text" name="collision[datum_id]" value="<%= (Datum.last).id %>" placeholder="<%= (Datum.last).id %>" readonly>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/collisions/edit.html.erb
<h1>Editing Collision</h1>

<%= render 'form', collision: @collision %>

<%= link_to 'Show', @collision %> |
<%= link_to 'Back', collisions_path %>

app/views/collisions/index.html.erb
<p id="notice"><%= notice %></p>

<div class="d-flex justify-content-between">
  <div><h1>Collisions</h1></div>
  <div class="ms-5"><%= paginate @collisions, window: 3, outer_window: 3 %></div>
</div>

<table class="table table-striped table-hover">
  <thead class="table-dark">
    <tr>
      <th>Bird</th>
      <th>Datum</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @collisions.each do |collision| %>
      <tr>
        <td><%= collision.bird.common_name %></td>
        <td><%= link_to collision.datum_id, data_url(datum_id: collision.datum_id), class: 'text-decoration-none' %></td>
        <td><% if can? :show, Collision %><%= link_to 'Show', collision, class: 'btn btn-sm btn-primary' %><% end %></td>
        <td><% if can? :update, Collision %><%= link_to 'Edit', edit_collision_path(collision), class: 'btn btn-sm btn-secondary' %><% end %></td>
        <td><% if can? :destroy, Collision %><%= link_to 'Destroy', collision, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-sm btn-danger' %><% end %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<% if can? :create, Collision %>
<%= link_to 'New Collision', new_flight_path, class: 'btn btn-sm btn-success' %>
<%= link_to 'Use last datum', new_collision_path, class: 'btn btn-sm btn-success' %>
<%#= link_to 'New Collision', new_collision_path %>
<% end %>

app/views/collisions/new.html.erb
<h1>New Collision</h1>

<%= render 'form', collision: @collision %>

<%= link_to 'Back', collisions_path %>

app/views/collisions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Bird:</strong>
  <%= @collision.bird.common_name %>
</p>

<p>
  <strong>Datum:</strong>
  <%= @collision.datum_id %>
</p>

<%= link_to 'Edit', edit_collision_path(@collision) %> |
<%= link_to 'Back', collisions_path %>