config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :collisions
  resources :data
  resources :weathers
  resources :reports
  resources :flights
  resources :aircrafts
  resources :pilots
  resources :birds
  resources :airports
  resources :cities
  resources :states
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  root to: "airports#index"
end

app/models/ability.rb
# frozen_string_literal: true

class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
       user ||= User.new # guest user (not logged in)
       if user.id == 1
        can :manage, :all
       elsif user.id != nil
        can :read, :all
        cannot :read, User
        cannot :show, :all
        can :read, User, :id => user.id
        can :update, User, :id => user.id
       else
        can :read, [Airport,Bird]
        cannot :show, [Airport,Bird]
        can :create, User
       end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/aircraft.rb
class Aircraft < ApplicationRecord
    has_many :flights

    validates :category, :certification, :model, presence: true

    paginates_per 8

    def model_certification
        model + " (" + certification + ")"
    end
end

app/models/airport.rb
class Airport < ApplicationRecord
  belongs_to :city
  has_many :data
  has_many :collisions, through: :data

  validates :name, presence: true, uniqueness: true
  validates :category, presence: true

  paginates_per 8
end

app/models/bird.rb
class Bird < ApplicationRecord
    has_many :collisions

    validates :common_name, :scientific_name, presence: true, uniqueness: true

    paginates_per 8
end

app/models/city.rb
class City < ApplicationRecord
  belongs_to :state
  has_many :airports

  validates :name, presence: true

  paginates_per 8
end

app/models/collision.rb
class Collision < ApplicationRecord
  belongs_to :bird
  belongs_to :datum

  paginates_per 8
end

app/models/datum.rb
class Datum < ApplicationRecord
  belongs_to :airport
  belongs_to :flight
  belongs_to :weather
  belongs_to :report
  has_many :collisions

  validates :date, :flight_phase, presence: true

  paginates_per 8
end

app/models/flight.rb
class Flight < ApplicationRecord
  belongs_to :aircraft
  belongs_to :pilot
  has_many :data

  paginates_per 8
end

app/models/pilot.rb
class Pilot < ApplicationRecord
    has_many :flights

    validates :first_name, :last_name, :privilege_level, :document, :birth_date, presence: true
    validates :document, uniqueness: true

    paginates_per 8

    def full_name
        last_name + ", " + first_name
    end
end

app/models/report.rb
class Report < ApplicationRecord
    has_many :data

    validates :airline_expense, :airport_expense, :insurance_expense, :public_expense, :delayed_flights, :fatal_victims, presence: true

    paginates_per 8
end

app/models/state.rb
class State < ApplicationRecord
    has_many :cities
    
    validates :name, presence: true, uniqueness: true
    
    paginates_per 8
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/weather.rb
class Weather < ApplicationRecord
    has_many :data

    validates :celsius_temperature, :humidity, :wind_speed, :average_rainfall, :insolation, presence: true

    paginates_per 8
end

app/controllers/data_controller.rb
class DataController < ApplicationController
  before_action :set_datum, only: %i[ show edit update destroy ]
  load_and_authorize_resource

  # GET /data or /data.json
  def index
    @data = Datum.all
    @data = @data.where(id: params[:datum_id]) unless params[:datum_id].blank?
    @data = @data.page(params[:page] || 1)
  end

  # GET /data/1 or /data/1.json
  def show
  end

  # GET /data/new
  def new
    @datum = Datum.new
  end

  # GET /data/1/edit
  def edit
  end

  # POST /data or /data.json
  def create
    @datum = Datum.new(datum_params)

    respond_to do |format|
      if @datum.save
        format.html { redirect_to new_collision_path, notice: "Datum was successfully created." }
        format.json { render :show, status: :created, location: @datum }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @datum.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /data/1 or /data/1.json
  def update
    respond_to do |format|
      if @datum.update(datum_params)
        format.html { redirect_to @datum, notice: "Datum was successfully updated." }
        format.json { render :show, status: :ok, location: @datum }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @datum.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /data/1 or /data/1.json
  def destroy
    @datum.destroy
    respond_to do |format|
      format.html { redirect_to data_url, notice: "Datum was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_datum
      @datum = Datum.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def datum_params
      params.require(:datum).permit(:date, :flight_phase, :airport_id, :flight_id, :weather_id, :report_id)
    end
end

app/helpers/airports_helper.rb
module AirportsHelper
end

app/helpers/birds_helper.rb
module BirdsHelper
end

app/helpers/cities_helper.rb
module CitiesHelper
end

app/helpers/data_helper.rb
module DataHelper
end

app/helpers/flights_helper.rb
module FlightsHelper
end

app/helpers/pilots_helper.rb
module PilotsHelper
end

app/helpers/reports_helper.rb
module ReportsHelper
end

app/helpers/states_helper.rb
module StatesHelper
end

app/views/data/_form.html.erb
<%= form_with(model: datum) do |form| %>
  <% if datum.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(datum.errors.count, "error") %> prohibited this datum from being saved:</h2>

      <ul>
        <% datum.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :date %>
    <%= form.date_select :date, use_two_digit_numbers: true, order: [:day,:month,:year] %>
  </div>

  <div class="field">
    <%= form.label :flight_phase %>
    <select name="datum[flight_phase]">
      <option value="Takeoff">Takeoff</option>
      <option value="Climb">Climb</option>
      <option value="Cruise">Cruise</option>
      <option value="Descent">Descent</option>
      <option value="Approach">Approach</option>
    </select>
  </div>

  <div class="field">
    <%= form.label :airport_id %>
    <%= form.collection_select(:airport_id, Airport.all, :id, :name) %>
  </div>

  <div class="field">
    <%= form.label :flight_id %>
    <input type="text" name="datum[flight_id]" value="<%= (Flight.last).id %>" placeholder="<%= (Flight.last).id %>" readonly>
  </div>

  <div class="field">
    <%= form.label :weather_id %>
    <input type="text" name="datum[weather_id]" value="<%= (Weather.last).id %>" placeholder="<%= (Weather.last).id %>" readonly>
  </div>

  <div class="field">
    <%= form.label :report_id %>
    <input type="text" name="datum[report_id]" value="<%= (Report.last).id %>" placeholder="<%= (Report.last).id %>" readonly>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/data/edit.html.erb
<h1>Editing Datum</h1>

<%= render 'form', datum: @datum %>

<%= link_to 'Show', @datum %> |
<%= link_to 'Back', data_path %>

app/views/data/index.html.erb
<p id="notice"><%= notice %></p>

<div class="d-flex justify-content-between">
  <div><h1>Data</h1></div>
  <div class="ms-5"><%= paginate @data, window: 3, outer_window: 3 %></div>
</div>

<table class="table table-striped table-hover">
  <thead class="table-dark">
    <tr>
      <th>Date</th>
      <th>Flight phase</th>
      <th>Airport</th>
      <th>Flight id</th>
      <th>Weather id</th>
      <th>Report id</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @data.each do |datum| %>
      <tr>
        <td><%= datum.date.to_formatted_s(:long_ordinal) %></td>
        <td><%= datum.flight_phase %></td>
        <td><%= datum.airport.name %></td>
        <td><%= link_to datum.flight_id, flights_url(flight_id: datum.flight_id), class: 'text-decoration-none' %></td>
        <td><%= link_to datum.weather_id, weathers_url(weather_id: datum.weather_id), class: 'text-decoration-none' %></td>
        <td><%= link_to datum.report_id, reports_url(report_id: datum.report_id), class: 'text-decoration-none' %></td>
        <td><% if can? :show, Datum %><%= link_to 'Show', datum, class: 'btn btn-sm btn-primary' %><% end %></td>
        <td><% if can? :update, Datum %><%= link_to 'Edit', edit_datum_path(datum), class: 'btn btn-sm btn-secondary' %><% end %></td>
        <td><% if can? :destroy, Datum %><%= link_to 'Destroy', datum, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-sm btn-danger' %><% end %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<% if can? :create, Datum %><%= link_to 'New Datum', new_datum_path, class: 'btn btn-sm btn-success' %><% end %>

app/views/data/new.html.erb
<h1>New Datum</h1>

<%= render 'form', datum: @datum %>

<%= link_to 'Back', data_path %>

app/views/data/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Date:</strong>
  <%= @datum.date.to_formatted_s(:long_ordinal) %>
</p>

<p>
  <strong>Flight phase:</strong>
  <%= @datum.flight_phase %>
</p>

<p>
  <strong>Airport:</strong>
  <%= @datum.airport_id %>
</p>

<p>
  <strong>Flight:</strong>
  <%= @datum.flight_id %>
</p>

<p>
  <strong>Weather:</strong>
  <%= @datum.weather_id %>
</p>

<p>
  <strong>Report:</strong>
  <%= @datum.report_id %>
</p>

<%= link_to 'Edit', edit_datum_path(@datum) %> |
<%= link_to 'Back', data_path %>